import { stages } from './domain/fire.ts';
import type { Stage, Goal } from './domain/fire.ts';
export const icons = {
  engine: '<svg viewBox="0 0 48 40" aria-hidden="true"><path d="M3 17h30v15H3Z" fill="#ce7967"/><path d="M33 13h10l4 8v11H33Z" fill="#d98b73"/><path d="M35 16h6l3 7h-9Z" fill="#b6dbd9"/><path d="M5 20h9v8H5m4-8v8m8-8h12v8H17" fill="#c4cbbb"/><path d="M3 29h43" stroke="#fff0c8" stroke-width="3"/><path d="M33 10h9" stroke="#e0a16d" stroke-width="4"/><circle cx="11" cy="33" r="5" fill="#526c66"/><circle cx="38" cy="33" r="5" fill="#526c66"/></svg>',
  ladder: '<svg viewBox="0 0 48 40" aria-hidden="true"><path d="M2 24h32v9H2Z" fill="#c97b69"/><path d="M34 16h9l4 7v10H34Z" fill="#d59276"/><path d="M36 18h6l2 6h-8Z" fill="#b6dbd9"/><path d="M13 25L31 3m-11 23L37 6M19 18l6 5m-1-10 6 5m-1-11 6 5" stroke="#afbeb0" stroke-width="3"/><path d="M30 3h14v9H30Z" fill="none" stroke="#e5c98f" stroke-width="3"/><circle cx="10" cy="34" r="5" fill="#526c66"/><circle cx="38" cy="34" r="5" fill="#526c66"/></svg>',
  ambulance: '<svg viewBox="0 0 48 40" aria-hidden="true"><path d="M3 12h30v21H3Z" fill="#f5edda" stroke="#b1c4b6"/><path d="M33 17h10l4 7v9H33Z" fill="#e9e3cc"/><path d="M35 19h6l3 6h-9Z" fill="#acd3d4"/><path d="M3 29h43M14 21h10m-5-5v10" stroke="#80ad9e" stroke-width="4"/><path d="M34 13h8" stroke="#d89779" stroke-width="3"/><circle cx="11" cy="34" r="5" fill="#526c66"/><circle cx="38" cy="34" r="5" fill="#526c66"/></svg>',
};
export const names: Record<Stage, string> = { dispatch: '消防隊出動！', hose: '消防車 · 接好水管', 'ground-fire': '消防車 · 幫忙滅火', 'ladder-arrival': '雲梯車來了', 'roof-reach': '雲梯車 · 伸到屋簷', 'roof-fire': '雲梯車 · 澆熄屋簷', rescue: '雲梯車 · 接大家下來', stowing: '大家都安全下來了', ambulance: '救護車 · 準備接送', stretcher: '救護員來幫忙', boarding: '平安送上救護車', departure: '一起出發去醫院', complete: '大家都平安了！' };
export const instructions: Record<Stage, string> = { dispatch: '按住消防車，拖到停車位', hose: '把水管頭拖到消防栓', 'ground-fire': '按住火苗，水柱跟著手指走', 'ladder-arrival': '雲梯車來幫忙了', 'roof-reach': '把工作籃拖向屋簷', 'roof-fire': '按住屋簷的火苗，慢慢澆熄', rescue: '拖工作籃，先接誰都可以', stowing: '收好雲梯，準備接送', ambulance: '把救護車拖到接送車位', stretcher: '把擔架拖到居民身旁', boarding: '把擔架拖回救護車後面', departure: '繫好了，平安出發', complete: '居民平安到醫院，小貓也回家了' };
export const goalNames: Record<Goal, string> = { hydrant: '消防栓', roof: '屋簷', resident: '居民', cat: '小貓', patient: '居民身旁', ambulance: '救護車後門' };
const hospital = '<svg viewBox="0 0 300 125" role="img" aria-label="救護車抵達醫院，醫護人員迎接居民"><path d="M0 105h300" stroke="#b7cbbb" stroke-width="12"/><path d="M153 26h118v76H153Z" fill="#f7efdb" stroke="#c6d6c3" stroke-width="3"/><path d="M144 24h136" stroke="#8bb4a4" stroke-width="9"/><path d="M181 65h42v37h-42Z" fill="#abd0cc"/><path d="M231 42h22v24h-22Z" fill="#abd0cc"/><path d="M178 34v20m-10-10h20" stroke="#8bb4a4" stroke-width="7"/><g class="hospital-van"><path d="M17 64h65v38H17Z" fill="#f3ecd8" stroke="#c1cbb5"/><path d="M82 76h22l14 15v11H82Z" fill="#f1e5c9"/><path d="M88 78h12l11 12H88Z" fill="#acd3d4"/><path d="M19 94h96m-70-22v17m-8-8h16" stroke="#80ad9e" stroke-width="5"/><path d="M86 71h13" stroke="#d9977e" stroke-width="4"/><circle cx="36" cy="104" r="8" fill="#627d76"/><circle cx="99" cy="104" r="8" fill="#627d76"/></g><g transform="translate(140 82)"><circle cy="-12" r="8" fill="#e7be94"/><path d="M-9-3H9V21H-9Z" fill="#f7f0db"/><path d="M-5 21v8m10-8v8" stroke="#80a999" stroke-width="5"/><path class="hospital-wave" d="M8 1l12-13" stroke="#f7f0db" stroke-width="6" stroke-linecap="round"/></g></svg>';
export function mountFireUI(app: HTMLElement, dev: boolean) {
  app.innerHTML = `<main class="world fire-world" aria-label="小小城市隊消防救援任務"><div class="canvas-host"></div><div class="fire-targets"></div><header class="masthead"><span class="brand-symbol" aria-hidden="true">▰</span><div><strong>小小城市隊</strong><span>TOWN CREW</span></div></header><div class="controls"><button class="home" aria-label="回到選關">⌂</button><button class="sound" aria-label="關閉音效" aria-pressed="false">♪</button><button class="restart" aria-label="重新開始消防救援任務">↻</button></div><div class="house-caption"><span class="house-instruction"></span><span class="house-detail"></span></div><div class="mission-badge"><span class="badge-icon">${icons.engine}</span><div><span class="eyebrow">消防隊，來幫忙</span><strong id="vehicle-name"></strong></div></div><div class="mission-steps" aria-label="消防救援三種車輛">${Object.entries(icons).map(([id, icon]) => `<span data-step="${id}">${icon}</span>`).join('')}</div><div class="progress" role="progressbar" aria-label="消防救援進度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span></span></div><div class="rescue-tally" hidden><span data-rescue="resident">居民 <b>○</b></span><span data-rescue="cat">小貓 <b>○</b></span></div><div class="hospital-arrival" hidden>${hospital}<span>平安到醫院了</span></div><div class="finish-actions" hidden><button class="finish-restart">↻ 再玩一次</button><button class="finish-home">⌂ 回到選關</button></div><div class="loading" role="status">消防隊準備出發…</div></main>${dev ? `<aside class="dev-panel"><div class="dev-heading">開發工具 · 消防救援</div><h1>消防隊，來幫忙。</h1><p class="dev-intro">接水 → 滅火 → 兩趟救援 → 平安接送</p><label class="field">直達階段<select id="stage">${stages.map(stage => `<option value="${stage}">${names[stage]}</option>`).join('')}</select></label><button class="reset-stage">重設目前階段</button><dl class="telemetry"><div><dt>目前階段</dt><dd id="phase"></dd></div><div><dt>動作</dt><dd id="action"></dd></div><div><dt>火點熄滅</dt><dd id="extinguished"></dd></div><div><dt>已救下</dt><dd id="rescued"></dd></div></dl><p class="dev-note">重新載入保留進度，回到選關後重新開始。</p></aside>` : ''}`;
}
