import { stages } from './domain/police.ts';
import type { Stage, PoliceState } from './domain/police.ts';
import { patrolIcon, bikeIcon, vanIcon } from '../../app/police-art.ts';
export const names: Record<Stage, string> = { intro: '警察隊，出動！', pursuit: '警車 · 跟進目標車', bikes: '重機 · 分路包抄', arrest: '合作到位，逮捕犯人', clearance: '警車 · 讓出接送通道', van: '偵防車 · 進場接人', door: '偵防車 · 打開側門', boarding: '警員陪同上車', lead: '重機 · 前方開道', transport: '偵防車 · 出發押送', depart: '車隊依序離場', complete: '任務完成，謝謝小小警察！' };
export function instruction(s: PoliceState) {
  const instructions: Record<Stage, string> = { intro: '包包被拿走了，警察隊來幫忙', pursuit: '拖警車跟上前方車輛', bikes: '先選一台重機，拖向發亮的目的地', arrest: '三方到位，警員上前逮捕', clearance: '把警車拖到警戒位，讓出通道', van: '把偵防車拖到接送位置', door: '沿箭頭拉開側滑門', boarding: '陪同上車，再關好車門', lead: '拖重機繞到前方，帶領車隊', transport: '拖偵防車，沿通道出發', depart: '警車和另一台重機跟上，平安回警局', complete: '失物回家了，警察隊也完成任務！' };
  return instructions[s.phase];
}
export function mountPoliceUI(app: HTMLElement, dev: boolean) {
  const icons = [patrolIcon, bikeIcon, bikeIcon, vanIcon];
  app.innerHTML = `<main class="world police-world" aria-label="小小警察隊任務"><div class="canvas-host"></div><div class="police-targets"></div><header class="masthead"><span class="brand-symbol" aria-hidden="true">▰</span><div><strong>小小城市隊</strong><span>TOWN CREW</span></div></header><div class="controls"><button class="home" aria-label="回到選關">⌂</button><button class="sound" aria-label="關閉音效" aria-pressed="false">♪</button><button class="restart" aria-label="重新開始警察任務">↻</button></div><div class="house-caption"><span class="house-instruction"></span><span class="house-detail"></span></div><div class="mission-badge"><span class="badge-icon">${patrolIcon}</span><div><span class="eyebrow">小小警察隊，一起合作</span><strong id="vehicle-name"></strong></div></div><div class="mission-steps" aria-label="警車、兩台重機與偵防車">${icons.map((icon, i) => `<span data-step="${i}">${icon}</span>`).join('')}</div><div class="progress" role="progressbar" aria-label="警察任務進度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span></span></div><div class="bike-picker" hidden><button data-bike="bike0" aria-label="先派一號重機">${bikeIcon}<span>1</span></button><button data-bike="bike1" aria-label="先派二號重機">${bikeIcon}<span>2</span></button></div><div class="police-arrival hospital-arrival" hidden><svg viewBox="0 0 300 125" aria-label="偵防車抵達警局"><path d="M0 107h300" stroke="#b7cbbb" stroke-width="12"/><path d="M151 28h130v78H151Z" fill="#f0dfba"/><path d="M144 26h143" stroke="#88a9ad" stroke-width="10"/><path d="M166 57h26v27h-26Z M236 57h26v27h-26Z" fill="#b5d6d2"/><path d="M200 64h27v42h-27Z" fill="#88a9ad"/><path d="m214 36 9 4v9l-9 6-9-6v-9Z" fill="#d9b466"/><g transform="translate(6 51)"><g class="hospital-van">${vanIcon.replace('<svg viewBox="0 0 116 64" aria-hidden="true">', '').replace('</svg>', '')}</g></g></svg><span>抵達警局，完成押送！</span></div><div class="finish-actions" hidden><button class="finish-restart">↻ 再玩一次</button><button class="finish-home">⌂ 回到選關</button></div><div class="loading" role="status">警察隊準備出發…</div></main>${dev ? `<aside class="dev-panel"><div class="dev-heading">開發工具 · 警察隊</div><h1>分路包抄，合作押送。</h1><p class="dev-intro">警車 → 兩台重機 → 偵防車</p><label class="field">直達階段<select id="stage">${stages.map(p => `<option value="${p}">${names[p]}</option>`).join('')}</select></label><button class="reset-stage">重設目前階段</button><label class="field">協作配置<select id="layout"><option value="0">左側攔停 · 左側接送</option><option value="1">左側攔停 · 右側接送</option><option value="2">右側攔停 · 左側接送</option><option value="3">右側攔停 · 右側接送</option></select></label><dl class="telemetry"><div><dt>目前階段</dt><dd id="phase"></dd></div><div><dt>動作</dt><dd id="action"></dd></div></dl><p class="dev-note">重設階段保留配置；重載與 HMR 保留進度。</p></aside>` : ''}`;
}
