import { stages } from './domain/mountain.ts';
import type { Stage, MountainState } from './domain/mountain.ts';
import { mountainIcons } from '../../app/mountain-art.ts';
export const names: Record<Stage, string> = { intro: '工程隊 · 山路搶通', push: '推土機 · 集中土石', 'dozer-exit': '推土機 · 讓出裝車區', 'truck-arrival': '砂石車 · 進場等候', 'excavator-arrival': '挖土機 · 準備裝車', excavate: '挖土機 · 搬走大石頭', 'excavator-exit': '挖土機 · 收好機臂', haul: '砂石車 · 載走土石', 'truck-exit': '砂石車 · 清運出發', 'sweeper-arrival': '清掃車 · 準備清掃', sweep: '清掃車 · 刷乾淨山路', 'sweeper-exit': '清掃車 · 完成收工', reopen: '山路通了，小車出發！', complete: '山路搶通，謝謝小小幫手！' };
export function instruction(s: MountainState) {
  if (s.phase === 'excavate') return s.motion === 'lift' ? '挖起來了，抬高大石頭' : s.motion === 'unload' ? '對準車斗，把土石裝進去' : s.motion === 'return' ? '挖斗回來，再搬下一塊' : s.carried !== null ? '把挖斗或大石頭拖到砂石車車斗' : '拖挖斗到想搬的大石頭';
  if (s.phase === 'push') return s.motion === 'push-return' ? '抬起刮板，退回再推另一堆' : '沿箭頭拖推土機，把土石集中到山側';
  const text: Partial<Record<Stage, string>> = { intro: '土石擋住了山路，工程隊來幫忙', 'dozer-exit': '開出作業通道，推土機先收工', 'truck-arrival': '空砂石車到山側等候', 'excavator-arrival': '挖土機停好，準備搬大石頭', 'excavator-exit': '三塊都裝好了，讓砂石車出發', haul: '載好了，沿箭頭拖砂石車出發', 'truck-exit': '把土石運走，留出清掃通道', 'sweeper-arrival': '清掃車來刷掉剩下的砂土', sweep: '拖清掃車，沿山路慢慢刷乾淨', 'sweeper-exit': '刷乾淨了，清掃車收工', reopen: '收好路障，讓等候的小車通過', complete: '謝謝你，大家又可以走山路了！' };
  return text[s.phase] ?? '';
}
export function step(s: MountainState) { const i = stages.indexOf(s.phase); return i <= 2 ? 0 : i <= 6 ? 1 : i <= 8 ? 2 : 3; }
export function mountMountainUI(app: HTMLElement, dev: boolean) {
  app.innerHTML = `<main class="world mountain-world" aria-label="小小城市隊山路搶通任務"><div class="canvas-host"></div><div class="mountain-targets"></div><div class="mountain-grip" aria-hidden="true" hidden></div><header class="masthead"><span class="brand-symbol" aria-hidden="true">▰</span><div><strong>小小城市隊</strong><span>TOWN CREW</span></div></header><div class="controls"><button class="home" aria-label="回到選關">⌂</button><button class="sound" aria-label="關閉音效" aria-pressed="false">♪</button><button class="restart" aria-label="重新開始山路搶通任務">↻</button></div><div class="house-caption"><span class="house-instruction"></span><span class="house-detail"></span></div><div class="mission-badge"><span class="badge-icon">${mountainIcons[0]}</span><div><span class="eyebrow">山路搶通，一起合作</span><strong id="vehicle-name"></strong></div></div><div class="mission-steps" aria-label="推土機、挖土機、砂石車與清掃車">${mountainIcons.map((art, i) => `<span data-step="${i}">${art}</span>`).join('')}</div><div class="progress" role="progressbar" aria-label="山路搶通進度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span></span></div><div class="success" role="status" aria-label="山路搶通完成" hidden>✓</div><div class="finish-actions" hidden><button class="finish-restart">↻ 再玩一次</button><button class="finish-home">⌂ 回到選關</button></div><div class="loading" role="status">工程隊準備出發…</div></main>${dev ? `<aside class="dev-panel"><div class="dev-heading">開發工具 · 山路搶通</div><h1>一起，讓山路通車。</h1><p class="dev-intro">推土 → 裝車 → 清運 → 清掃 → 通車</p><label class="field">直達階段<select id="stage">${stages.map(p => `<option value="${p}">${names[p]}</option>`).join('')}</select></label><button class="reset-stage">重設目前階段</button><label class="field">落石分布<select id="pattern"><option value="spread">前後散落</option><option value="cluster">集中落石</option></select></label><label class="field">施工方向<select id="layout"><option value="0">挖土機在左</option><option value="1">挖土機在右</option></select></label><dl class="telemetry"><div><dt>目前階段</dt><dd id="phase"></dd></div><div><dt>動作</dt><dd id="action"></dd></div></dl><p class="dev-note">重設階段保留配置；重載與 HMR 保留工作進度。</p></aside>` : ''}`;
}
