import { stages, towType, towDirection } from './domain/traffic.ts';
import type { Stage, Goal, TrafficState } from './domain/traffic.ts';
const icon = (body: string, extra: string) => `<svg viewBox="0 0 48 40" aria-hidden="true"><path d="M3 17h30v15H3Z" fill="${body}"/><path d="M33 14h9l5 10v8H33Z" fill="${body}"/><path d="M35 17h5l4 7h-9Z" fill="#b6dcd9"/>${extra}<circle cx="11" cy="33" r="5" fill="#526c66"/><circle cx="38" cy="33" r="5" fill="#526c66"/></svg>`;
export const icons = {
  police: icon('#eee8d5', '<path d="M3 27h43" stroke="#749aaf" stroke-width="5"/><path d="M18 13h12" stroke="#d58d7b" stroke-width="4"/>'),
  tow: icon('#e3b360', '<path d="M2 25h30v5H2Z" fill="#7f9b95"/><path d="M8 14h18v10H8Z" fill="#d8947e"/><path d="M11 10h11v6H11Z" fill="#b3d6ce"/>'),
  sweeper: icon('#9aba9d', '<path d="M6 13h23v14H6Z" fill="#b4c8a7"/><path d="M8 17h18m-18 4h18" stroke="#809d8d" stroke-width="2"/><ellipse cx="29" cy="34" rx="9" ry="3" fill="#d9bb7a"/>'),
  ambulance: icon('#f0e9d5', '<path d="M3 29h43M14 21h10m-5-5v10" stroke="#80ad9e" stroke-width="4"/><path d="M34 11h8" stroke="#d89779" stroke-width="3"/>'),
};
export const liftIcon = icon('#e3b360', '<path d="M29 18 11 5 3 23" fill="none" stroke="#809b93" stroke-width="4"/><path d="M3 23v5h12" fill="none" stroke="#eac87e" stroke-width="3"/>');
export const names: Record<Stage, string> = { collision: '小碰撞，大家來幫忙', police: '警車 · 安全停靠', cones: '警員 · 圍好事故區', 'tow-choice': '先幫哪台小客車？', 'tow-arrival': '拖吊車來了', hook: '拖吊車 · 接上掛鉤', 'tow-exit': '拖吊車 · 送去修理', sweeper: '清掃車 · 準備清掃', sweep: '清掃車 · 刷乾淨道路', ambulance: '救護車 · 準備接送', stretcher: '救護員來幫忙', boarding: '平安送上救護車', departure: '一起出發去醫院', reopen: '收好交通錐，恢復通車', complete: '道路乾淨，大家平安！' };
export const instructions: Record<Stage, string> = { collision: '小車停下來，居民到路旁等候', police: '把警車拖到停車位', cones: '把交通錐拖到發亮的輪廓', 'tow-choice': '點一台小客車，呼叫拖吊車', 'tow-arrival': '拖吊車慢慢倒進來', hook: '把拖吊工具拖到選好的小客車', 'tow-exit': '載好了，把拖吊車往外拖', sweeper: '把清掃車拖到道路起點', sweep: '按住清掃車，往右刷乾淨', ambulance: '把救護車拖到接送車位', stretcher: '把擔架拖到居民身旁', boarding: '把擔架拖回救護車後門', departure: '繫好了，平安出發', reopen: '警員收好交通錐，小車可以通過了', complete: '謝謝你，一起讓小鎮恢復通車' };
export const goalNames: Record<Goal, string> = { 'cone-left': '交通錐', 'cone-right': '交通錐', 'car-0': '小客車', 'car-1': '小客車', patient: '居民身旁', ambulance: '救護車後門' };
export function instruction(s: TrafficState, nearGoal: boolean) {
  if (s.phase === 'hook' && s.action === 'working') return towType(s) === 'flatbed' ? '接好了，慢慢拉上平板' : '托好了，慢慢抬起前輪';
  if (nearGoal) return '對準了，幫你接好！';
  if (s.phase === 'hook') return towType(s) === 'flatbed' ? '把掛鉤拖到選好的小客車' : '把托輪架拖到選好的小客車';
  if (s.phase === 'tow-exit') return towDirection(s) < 0 ? '載好了，把拖吊車往左拖' : '載好了，把拖吊車往右拖';
  return instructions[s.phase];
}
export function mountTrafficUI(app: HTMLElement, dev: boolean) {
  app.innerHTML = `<main class="world traffic-world" aria-label="小小城市隊交通救援任務"><div class="canvas-host"></div><div class="traffic-targets"></div><header class="masthead"><span class="brand-symbol" aria-hidden="true">▰</span><div><strong>小小城市隊</strong><span>TOWN CREW</span></div></header><div class="controls"><button class="home" aria-label="回到選關">⌂</button><button class="sound" aria-label="關閉音效" aria-pressed="false">♪</button><button class="restart" aria-label="重新開始交通救援任務">↻</button></div><div class="house-caption"><span class="house-instruction"></span><span class="house-detail"></span></div><div class="mission-badge"><span class="badge-icon">${icons.police}</span><div><span class="eyebrow">交通救援隊，來幫忙</span><strong id="vehicle-name"></strong></div></div><div class="mission-steps" aria-label="交通救援四種車輛">${Object.entries(icons).map(([id, art]) => `<span data-step="${id}">${art}</span>`).join('')}</div><div class="progress" role="progressbar" aria-label="交通救援進度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span></span></div><div class="traffic-tally" aria-label="已送修的小客車"><span data-car="0"><svg viewBox="0 0 48 30" aria-hidden="true"><path d="M3 13h42v11H3Z M11 5h23l5 11H7Z" fill="currentColor"/><circle cx="12" cy="24" r="4" fill="#627d77"/><circle cx="37" cy="24" r="4" fill="#627d77"/></svg><b>○</b></span><span data-car="1"><svg viewBox="0 0 48 30" aria-hidden="true"><path d="M3 13h42v11H3Z M11 5h23l5 11H7Z" fill="currentColor"/><circle cx="12" cy="24" r="4" fill="#627d77"/><circle cx="37" cy="24" r="4" fill="#627d77"/></svg><b>○</b></span></div><div class="finish-actions" hidden><button class="finish-restart">↻ 再玩一次</button><button class="finish-home">⌂ 回到選關</button></div><div class="loading" role="status">交通救援隊準備出發…</div></main>${dev ? `<aside class="dev-panel"><div class="dev-heading">開發工具 · 交通救援</div><h1>讓小鎮恢復通車。</h1><p class="dev-intro">管制 → 兩趟拖吊 → 清掃 → 接送</p><label class="field">直達階段<select id="stage">${stages.map(s => `<option value="${s}">${names[s]}</option>`).join('')}</select></label><button class="reset-stage">重設目前階段</button><dl class="telemetry"><div><dt>目前階段</dt><dd id="phase"></dd></div><div><dt>動作</dt><dd id="action"></dd></div></dl><p class="dev-note">重載與 HMR 保留進度；開發存檔獨立。</p></aside>` : ''}`;
}
