import { stages, towType, towDirection } from './domain/traffic.ts';
import type { Stage, Goal, TrafficState } from './domain/traffic.ts';
import { icons, liftIcon } from '../../app/traffic-vehicle-art.ts';
export { icons, liftIcon } from '../../app/traffic-vehicle-art.ts';
export const names: Record<Stage, string> = { collision: '小碰撞，大家來幫忙', police: '警車 · 安全停靠', cones: '警員 · 圍好事故區', 'tow-arrival': '拖吊車來了', hook: '拖吊車 · 接上掛鉤', 'tow-exit': '拖吊車 · 送去修理', sweeper: '清掃車 · 準備清掃', sweep: '清掃車 · 刷乾淨道路', ambulance: '救護車 · 準備接送', stretcher: '救護員來幫忙', boarding: '平安送上救護車', departure: '一起出發去醫院', reopen: '收好交通錐，恢復通車', complete: '道路乾淨，大家平安！' };
export const instructions: Record<Stage, string> = { collision: '小車停下來，居民到路旁等候', police: '把警車拖到停車位', cones: '把交通錐拖到發亮的輪廓', 'tow-arrival': '拖吊車慢慢倒進來', hook: '把拖吊工具拖到想救的小客車', 'tow-exit': '載好了，把拖吊車往外拖', sweeper: '把清掃車拖到道路起點', sweep: '按住清掃車，往右刷乾淨', ambulance: '把救護車拖到接送車位', stretcher: '把擔架拖到居民身旁', boarding: '把擔架拖回救護車後門', departure: '繫好了，平安出發', reopen: '警員收好交通錐，小車可以通過了', complete: '謝謝你，一起讓小鎮恢復通車' };
export const goalNames: Record<Goal, string> = { 'cone-left': '交通錐', 'cone-right': '交通錐', 'car-0': '小客車', 'car-1': '小客車', patient: '居民身旁', ambulance: '救護車後門' };
export function instruction(s: TrafficState, nearGoal: boolean) {
  if (s.phase === 'hook' && s.action === 'working') return towType(s) === 'flatbed' ? '接好了，慢慢拉上平板' : '托好了，慢慢抬起前輪';
  if (nearGoal) return '對準了，幫你接好！';
  if (s.phase === 'hook') return towType(s) === 'flatbed' ? '把掛鉤拖到想救的小客車' : '把托輪架拖到想救的小客車';
  if (s.phase === 'tow-exit') return towDirection(s) < 0 ? '載好了，把拖吊車往左拖' : '載好了，把拖吊車往右拖';
  return instructions[s.phase];
}
export function mountTrafficUI(app: HTMLElement, dev: boolean) {
  app.innerHTML = `<main class="world traffic-world" aria-label="小小城市隊交通救援任務"><div class="canvas-host"></div><div class="traffic-targets"></div><header class="masthead"><span class="brand-symbol" aria-hidden="true">▰</span><div><strong>小小城市隊</strong><span>TOWN CREW</span></div></header><div class="controls"><button class="home" aria-label="回到選關">⌂</button><button class="sound" aria-label="關閉音效" aria-pressed="false">♪</button><button class="restart" aria-label="重新開始交通救援任務">↻</button></div><div class="house-caption"><span class="house-instruction"></span><span class="house-detail"></span></div><div class="mission-badge"><span class="badge-icon">${icons.police}</span><div><span class="eyebrow">交通救援隊，來幫忙</span><strong id="vehicle-name"></strong></div></div><div class="mission-steps" aria-label="交通救援四種車輛">${Object.entries(icons).map(([id, art]) => `<span data-step="${id}">${art}</span>`).join('')}</div><div class="progress" role="progressbar" aria-label="交通救援進度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span></span></div><div class="traffic-tally" aria-label="已送修的小客車"><span data-car="0"><svg viewBox="0 0 48 30" aria-hidden="true"><path d="M3 13h42v11H3Z M11 5h23l5 11H7Z" fill="currentColor"/><circle cx="12" cy="24" r="4" fill="#627d77"/><circle cx="37" cy="24" r="4" fill="#627d77"/></svg><b>○</b></span><span data-car="1"><svg viewBox="0 0 48 30" aria-hidden="true"><path d="M3 13h42v11H3Z M11 5h23l5 11H7Z" fill="currentColor"/><circle cx="12" cy="24" r="4" fill="#627d77"/><circle cx="37" cy="24" r="4" fill="#627d77"/></svg><b>○</b></span></div><div class="finish-actions" hidden><button class="finish-restart">↻ 再玩一次</button><button class="finish-home">⌂ 回到選關</button></div><div class="loading" role="status">交通救援隊準備出發…</div></main>${dev ? `<aside class="dev-panel"><div class="dev-heading">開發工具 · 交通救援</div><h1>讓小鎮恢復通車。</h1><p class="dev-intro">管制 → 兩趟拖吊 → 清掃 → 接送</p><label class="field">直達階段<select id="stage">${stages.map(s => `<option value="${s}">${names[s]}</option>`).join('')}</select></label><button class="reset-stage">重設目前階段</button><dl class="telemetry"><div><dt>目前階段</dt><dd id="phase"></dd></div><div><dt>動作</dt><dd id="action"></dd></div></dl><p class="dev-note">重載與 HMR 保留進度；開發存檔獨立。</p></aside>` : ''}`;
}
